
import Nav from '@/components/Nav';
import './globals.css';
import 'bootstrap/dist/css/bootstrap.min.css';



export const metadata = {
  title: 'Burger',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Nav />
        {children}

      </body>
    </html>
  )
}
